package com.lucastrevvos.kmonemotor.radar.core

object RadarFeatureFlags {
    const val PRODUCTION_LIKE_DEBUG_MODE = true

    const val ENABLE_DEBUG_SCREENSHOT_SAVE = false && !PRODUCTION_LIKE_DEBUG_MODE
    const val ENABLE_DEBUG_CROP_SAVE = true && !PRODUCTION_LIKE_DEBUG_MODE
    const val ENABLE_REGIONAL_OCR = true
    const val ENABLE_OCR_ON_FOLLOWUP = true
    const val ENABLE_OCR_ON_UNKNOWN = true
    const val ENABLE_OCR_ON_POST_TRANSITION = false
    const val ENABLE_DEBUG_OCR_SAVE = true && !PRODUCTION_LIKE_DEBUG_MODE
    const val ENABLE_DEBUG_FINGERPRINT_SAVE = true && !PRODUCTION_LIKE_DEBUG_MODE
    const val ENABLE_DEBUG_DEDUPE_SAVE = true && !PRODUCTION_LIKE_DEBUG_MODE
    const val ENABLE_DEBUG_PARSER_SAVE = true && !PRODUCTION_LIKE_DEBUG_MODE
    const val ENABLE_DEBUG_DECISION_SAVE = true && !PRODUCTION_LIKE_DEBUG_MODE
    const val ENABLE_DEBUG_PRESENTATION_SAVE = true && !PRODUCTION_LIKE_DEBUG_MODE
    const val MANUAL_ANALYSIS_COOLDOWN_MS = 2000L
    const val MANUAL_ANALYSIS_MIN_SCREENSHOT_INTERVAL_MS = 1500L
    const val AUTO_POST_TRANSITION_OVERRIDE_MAX_AGE_MS = 2500L
    const val AUTO_RECOVERY_COOLDOWN_MS = 1500L
    const val AUTO_CAPTURE_BURST_DELAY_MS = 300L
    const val AUTO_CAPTURE_BURST_MAX_DELAY_MS = 500L
    const val AUTO_CAPTURE_BURST_MAX_ATTEMPTS = 1
    const val AUTO_CAPTURE_BURST_MAX_AGE_MS = 2500L
    const val ENABLE_FLOATING_OBSTRUCTION_GUARD = true
}
