package com.lucastrevvos.kmonemotor.radar.core

enum class TriggerSource {
    UBER_FLOATING_WINDOW,
    UBER_FLOATING_OVER_99_DIAGNOSTIC,
    UBER_DOMINANT_OFFER_DIAGNOSTIC,
    UBER_PRE_OFFER_VISUAL_WATCHDOG,
    UBER_AUTO_BURST_RECOVERY,
    UBER_STATE_TRANSITION,
    DOMINANT_WINDOW_CHANGE,
    NINETY_NINE_TREE_STRUCTURE,
    NINETY_NINE_COMPACT_TREE_DIAGNOSTIC,
    MANUAL_SCREEN_ANALYSIS,
    MANUAL_DEBUG
}
